# dev-cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-cluster
  region: ap-south-1

managedNodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: m5.xlarge
    desiredCapacity: 1
    volumeSize: 20
    privateNetworking: true
  - name: ng-2-builders
    labels: { role: builders }
    instanceTypes: ["t3a.large", "m5a.large", "t3.large", "m5.large"]
    spot: true
    desiredCapacity: 1
    volumeSize: 10
    privateNetworking: true
